version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: etf_db
      MYSQL_ROOT_PASSWORD: group6700
      MYSQL_USER: etf_user
      MYSQL_PASSWORD: group6700
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db_setup.sql:/docker-entrypoint-initdb.d/db_setup.sql

volumes:
  mysql_data:
